[package]
name = "gdmarp"
version = "0.0.2"
authors = ["simoncreek <simoncreek@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
anyhow = "1.0.41"
fs_extra = "1.2.0"
