#!/bin/sh

# Reference source : https://stackoverflow.com/questions/7069682/how-to-get-arguments-with-flags-in-bash

# ----------
# VARIABLES
input=$PWD
output="$PWD"/build
include=""
sources=""
flag_preserve=false
flag_use_default=true
flag_use_docker=false
flag_init_code=false
flag_init_git=false
flag_init_make=false
flag_format=pptx
flag_modules=""
config=""
bin_name=$(basename "$0")
bin_path=$(dirname "$(readlink -f "$0")")
action=""

reset_var(){
	input=$PWD
	output="$PWD"/build
	include=""
	sources=""
	flag_preserve=false
	flag_use_default=true
	flag_use_docker=false
	flag_init_code=false
	flag_init_git=false
	flag_init_make=false
	flag_format=pptx
	flag_modules=""
	config=""
	bin_name=$(basename "$0")
	bin_path=$(dirname "$(readlink -f "$0")")
	action=""
}

# Marp path can be changed with a flat
marp=marp

# ----------
# FUNCTIONS

help_message(){
	echo "$bin_name - Compile markdown file into pptx file with predefined macro support."
	echo "Usage: [options] action [arguments]"
	echo " "
	echo "options:"
	echo "-h                    show brief help"
	echo "-I <DIR>              specify a m4 script directory to include"
	echo "-M <MODULES>          modules to include with execution"
	echo "-p                    preserve middle format"
	echo "-n                    do not apply default macro rules"
	echo "-d                    indicate docker usage. Docker image needs loose privilege."
	echo "-g                    initiate with git after gdmarp init and create gitignore file"
	echo "-S <TYPE>             add automation script"
	echo "-F <flag_format>           repr format to render"
	echo " "
	echo "actions:"
	echo "help                  show brief help messages"
	echo "init                  initiate file structure"
	echo "prep                  only pre-process m4 macros"
	echo "repr                  render representation form"
	echo "wiki                  push processed file into wiki website"
	echo "run                   run all scripts configured in config.json file"
	echo "check                 check installed dependencies"
	echo "test                  create html format for testing and preserve out.md file"
	echo "install-image         install latest gdmarp docker image"
}

gd_install(){
	docker pull simoncreek/gdmarp:latest
}

gd_init(){
	cp "$bin_path"/default/basic/* -rf "$input"

	[ "$flag_use_docker" = "true" ] && chmod 777 "$input"/build
	[ "$flag_init_git" = "true" ] && cd "$input" && git init && printf "build\nout.md" > .gitignore
	[ "$flag_init_make" = "true" ] && cp "$bin_path"/default/extra/Makefile -f "$input"/Makefile
	[ "$flag_init_code" = "true" ] && mkdir "$input"/.vscode && cp "$bin_path"/default/extra/tasks.json -f "$input"/.vscode/tasks.json

	# TODO | Currently withmods are a single item despite the name
	case $flag_modules in
		mw)
			readconfig

			config=$(printf '%s' "$config" | jq --arg bot_id id --arg bot_pwd password --arg page_title title '.env += {url: "wiki_url"} + {bot_id: $bot_id} + {bot_pwd: $bot_pwd } + {page_title: $page_title}')
			printf '%s' "$config" > "$input"/config.json
			;;
	esac
}

readconfig(){
	config=$(cat "$input"/config.json)
}

# Yet to complete
add_sources(){
	while test $# -gt 0; do
		case "$1" in 
			marp)
				sources="${sources} $MODULE/repr/marp/env.m4 $MODULE/repr/marp/macro.m4"
				shift
				;;
			mw)
				sources="${sources} $MODULE/wiki/mediawiki/env.m4 $MODULE/wiki/mediawiki/macro.m4"
				shift
				;;
			*)
				shift
				;;
		esac
	done
}

gd_preprocess(){
	# Literally read the config
	readconfig

	# Export environment variable
	export ROOT=$bin_path
	export MODULE=$bin_path/modules
	export SCRIPTS=$bin_path/m4/scripts

	# M4 include path
	[ -z "$include" ] && include=$PWD

	# Source files array to process
	# Word splitting is intended because there is no array in posix sh
	sources="$input"/index.m4
	# If default script is enabled or not disabled
	[ "$flag_use_default" = "true" ] && sources="${sources} $input/env.m4 $bin_path/m4/default.m4"
	# modules are references from flag option
	add_sources $flag_modules

	# Run main m4 functions
	m4 -I "$PWD" -I "$bin_path"/m4 -I "$bin_path"/m4/GNU -I "$include" $sources "$input"/index.md > "$input"/out.md

	# Process again for fragmented macro execution no sources needed
	m4 -I "$PWD" -I "$bin_path"/m4 -I "$bin_path"/m4/GNU -I "$include" $sources "$input"/out.md > "$input"/frag.md
	# This squahses multiple new lines into single new line
	awk '/./ { e=0 } /^$/ { e += 1 } e <= 1' < "$input"/frag.md > "$input"/out.md
	rm "$input"/frag.md

	# Sed for escape characters restoration
	sed -i -f "$SCRIPTS"/restore.sed "$input"/out.md
}

gd_repr(){
	# Preprocessing before marp compilation
	gd_preprocess

	# Compile with marp-cli
	if [ "$flag_use_docker" = "false" ]; then
		# No Docker
		mkdir -p "$output"
		$marp --allow-local-files --$flag_format --html "$input"/out.md -o "$output"/out.$flag_format
	else
		# With Docker
		mkdir -p "$output"
		docker run --rm --init -v "$input":/home/marp/app/ -e LANG="$LANG" marpteam/marp-cli out.md --$flag_format --allow-local-files --html -o build/out.$flag_format
	fi

	[ "$flag_preserve" = "false" ] && rm "$input"/out.md
}

gd_wiki(){
	# Preprocessing before sending out file
	gd_preprocess

	# No Docker code only for now
	# Make directory if not existant
	mkdir -p "$output"

	# Utilzie various backends
	case $flag_modules in
		mw)
			# TODO Rename this variables into screaming snake case
			# Export environment variables
			export bot_id=$(printf '%s' "$config" | jq .env.bot_id)
			export bot_pwd=$(printf '%s' "$config" | jq .env.bot_pwd)
			export page_title=$(printf '%s' "$config" | jq .env.page_title)

			# Return early if variable is null
			[ "$bot_id" = "null" ] && echo "Config's env is missing bot_id" && exit 0
			[ "$bot_pwd" = "null" ] && echo "Config's env is missing bot_pwd" && exit 0
			[ "$page_title" = "null" ] && echo "Config's env is missing page_title" && exit 0

			# TODO | Currently binary query is not complete
			node "$bin_path"/modules/wiki/mediawiki/mediawiki_bin/index.js "$input"/out.md "$input"/config.json
			;;
		*)
			echo "No proper module was given to render a wiki page"
			exit 0
			;;
	esac

	[ "$flag_preserve" = "false" ] && rm "$input"/out.md
}

gd_run(){
	# Read a config
	readconfig

	# Index
	i=0
	runner=$(echo "$config" | jq .script[$i] )
	while [ "$runner" != "null" ]
	do
		printf '> Executing script %s\n' "$runner"
		# Reset varaibles for fresh run
		reset_var
		# !! Do not quote the argument because gd_main expects non quoted arguments
		gd_main $(echo $runner | tr -d '"')
		i=$((i+1))
		runner=$(echo "$config" | jq .script[$i] )
	done
	echo "> Run finished"
}

gd_test(){
	gd_preprocess

	# Compile with marp-cli
	if [ "$flag_use_docker" = "false" ]; then
		# No Docker
		mkdir -p "$output"
		$marp --allow-local-files --html "$input"/out.md -o "$output"/out.html
	else
		# With Docker
		mkdir -p "$output"
		docker run --rm --init -v "$input":/home/marp/app/ -e LANG="$LANG" marpteam/marp-cli out.md --allow-local-files --html -o build/out.html
	fi
}

gd_check(){
	# Check binary installation
	# Currently m4 and awk is necessary regardless of docker image
	CLEAN=true
	echo "Checking m4 install..." && [ -z "$(command -v m4)" ] && echo "M4 not installed" && CLEAN=false
	echo "Checking awk install..." && [ -z "$(command -v awk)" ] && echo "Awk not installed" && CLEAN=false

	if [ "$flag_use_docker" = "false" ]; then
		echo "Checking google chrome install..." && [ -z "$(command -v google-chrome)" ] && echo "Chrome browser not installed or not found in path." \
			&& echo "Checking chromium install instead..." &&[ -z "$(command -v chromium)" ] && echo "Chromium not installed or not found in path". && CLEAN=false
		echo "Checking marp install..." && [ -z "$(command -v marp)" ] && echo "Marp cli not installed" && CLEAN=false
		[ "$CLEAN" = "true" ] && echo "Every dependencies are installed"
	else
		# Check docker installation
		# flag_use_docker CHECK
		echo "Checking marp-cli docker image installed"
		if [ "$(docker image ls | grep -c marpteam/marp-cli)" = "0" ]; then
			echo "ERR : Docker image is not installed"
			CLEAN=false
		fi
		[ "$CLEAN" = "true" ] && echo "Every dependencies are installed"
	fi
}

gd_main(){
	# No arg given print -h
	if [ $# -eq 0 ]; then
		help_message
		exit 0
	fi

	# Argument parse
	while [ $# -gt 0 ] ; do
		case "$1" in 
			-h)
				action=help_message
				break
				;;
			-I)
				if [ -n "$2" ]; then
					while [ -n "$2" ]; do
						case "$2" in
							# Next element is another flag
							-*)
								break
								;;
							*)
								include="${include} $2"
								shift
								;;
						esac
					done
					shift 
				else
					printf 'ERROR: "-I" requires a non-empty option argument.\n' >&2
					exit 1
				fi
				;;
			-d)
				flag_use_docker=true
				shift
				;;
			-c)
				marp="node /home/marp/.cli/marp-cli.js"
				shift
				;;
			-p)
				flag_preserve=true
				shift
				;;
			-n)
				flag_use_default=false
				shift
				;;
			-g)
				flag_init_git=true
				shift
				;;
			-M)
				if [ -n "$2" ]; then
					flag_modules=$2
					shift
				else
					printf 'ERROR: "-M" requires a non-empty option argument.\n' >&2
					exit 1
				fi
				shift
				;;
			-S)
				if [ -n "$2" ]; then
					case "$2" in
						"make")
							flag_init_make=true
							;;
						"code")
							flag_init_code=true
							;;
					esac
					shift
				else
					printf 'ERROR: "-S" requires a non-empty option argument.\n' >&2
					exit 1
				fi
				shift
				;;
			-F)
				if [ -n "$2" ]; then
					case "$2" in
						"pdf")
							flag_format=pdf
							;;
						"pptx")
							flag_format=pptx
							;;
					esac
					shift
				else
					printf 'ERROR: "-F" requires a non-empty option argument.\n' >&2
					exit 1
				fi
				shift
				;;
			help)
				action=help_message
				break
				;;
			init)
				action=gd_init
				shift
				;;
			repr)
				action=gd_repr
				shift
				;;
			wiki)
				action=gd_wiki
				shift
				;;
			run)
				action=gd_run
				shift
				;;
			install-image)
				action=gd_install
				shift
				;;
			prep)
				action=gd_preprocess
				shift
				;;
			test)
				action=gd_test
				shift
				;;
			check)
				action=gd_check
				shift
				;;
			*)
				shift
				;;
		esac
	done
	$action
	#exit 0
}

# ----------
# MAIN
# No quote is needed
gd_main $*
