#!/bin/sh

# Commands are ...
# Install docker 
# Simply redirect flags to docker 

call_docker() {
	# $* should be expanded not merged
	docker run --rm -v "$PWD":/home/marp/app --user="$(id -u):$(id -g)" \
	simoncreek/gdmarp $*
}

install_docker() {
	# Check if image is installed if not install
	# if image exists don't install again
	# docker pull simoncreek/gdmarp:latest
}

main() {
	[ "$1" = "install" ] && shift && install_docker $*
	[ "$1""$2" = "run--" ] && shift && call_docker $*
}

# This is main function
call_docker $*
